Make the doSave method compatible with Symfony\Component\Cache\Traits\AbstractTrait::doSave
ezsystems/symfony-tools pull request #12
Opened 2021-05-22 13:06 UTC by emodric

Current implementation is working fine, but in theory is not correct as it does not follow the rules of contravariance.

Moreover, it fails in PHP 8 (I am testing eZ Platform 2.5 on PHP 8 with `--ignore-platform-reqs`) as PHP 8 introduces the validation of abstract trait methods:

https://3v4l.org/hVGRg

Can this be merged and tagged since it does not introduce any breaking change and allows me to play with eZ Platform 2.5 on PHP 8?

Thanks!

2021-05-26 08:24 UTC, emodric commented
Ping @andrerom @alongosz

2021-05-26 12:48 UTC, alongosz requested changes
Tests are failing here.
It doesn't seem like it's compatible with Symfony 3.4 for which this package was created AFAIR, see https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/Cache/Traits/AbstractTrait.php#L80

2021-05-26 13:45 UTC, emodric commented
Tests themseves are passing:

![image](https://user-images.githubusercontent.com/362286/119670393-264e2180-be39-11eb-868a-5b563b418d05.png)

The issue with the build seems like a problem with PHP CS Fixer.

The method signature in Symfony 3.4 is `abstract protected function doSave(array $values, $lifetime);` which IS compatible with the new signature from this PR: `abstract protected function doSave(array $values, $lifetime, array $addTagData = [], array $removeTagData = []): array;`. Added arguments do not cause issues.

2021-05-26 13:57 UTC, Steveb-p commented
@alongosz It's from what I see a backport from Symfony 4.x, with parameter `$lifetime` being narrowed down to `int`. Type narrowing from undeclared type is allowed for PHP7, but prohibited by PHP8.

It looks good to me, I just didn't have the time to read into this one properly.

To be frank since this is a polyfill class it should be wrapped with `class_exists` check to prevent collision with Symfony classes it intends to polyfill, just in case, but that's beside the point.

2021-05-27 08:54 UTC, Steveb-p commented
@emodric to be on the safe side, could you please provide me with a detailed (relatively) error with stacktrace, so I can reproduce it in tests, and then attach them here?

I'm already setting up tests for PHP8 in some other packages of ours.

In the meantime until this is merged, could you please use your fork (with normal composer's repository overwrite, as per their docs)?

2021-05-27 09:27 UTC, emodric commented
@Steveb-p Actually, there's no stack trace since this is a fatal compile error, but the error message is:

```
[Symfony\Component\Debug\Exception\FatalErrorException]                                                                                                                                                         
Compile Error: Declaration of Symfony\Component\Cache\Adapter\AbstractTagAwareAdapter::doSave(array $values,
int $lifetime, array $addTagData = [], array $removeTagData = []): array must be compatible with
Symfony\Component\Cache\Traits\AbstractTrait::doSave(array $values, $lifetime)                                                                                                                                                                                                                                                                                                                                                    

at /var/www/html/ezplatform2/vendor/ezsystems/symfony-tools/
src/lib/Symfony/Components/Cache/Adapter/AbstractTagAwareAdapter.php:148
```

2021-05-28 07:28 UTC, Steveb-p commented
Added a branch with tests that show this particular issue, along with new CI pipeline: #13.

2021-05-28 14:20 UTC, Steveb-p commented
@emodric please rebase the branch on the current `master` and tests should lit up green.

2021-05-31 08:09 UTC, emodric commented
@Steveb-p Done!

2021-05-31 08:14 UTC, Steveb-p commented
Seems like some test classes also have invalid `setUp` declarations, which would blow the tests up. Can you fix those? If not I'll do that myself, in the evening.

2021-05-31 08:21 UTC, emodric commented
It looks like the tests that blow up actually come from Symfony.

2021-05-31 08:32 UTC, Steveb-p commented
We will need to use https://symfony.com/doc/current/components/phpunit_bridge.html#removing-the-void-return-type then.

Probably introducing trait usage here would be the least amount of work?

2021-05-31 10:03 UTC, emodric commented
Hm... Trait requires us to redefine `setUp` and friends as `doSetUp`, and since original methods are in `vendor/`, I don't think trait would help us.

I've added `SYMFONY_PHPUNIT_REMOVE_RETURN_TYPEHINT` environment variable instead.

Let's see what happens now.

2021-05-31 10:19 UTC, Steveb-p commented
I'm pretty sure PHPStan will complain about those methods. It's not aware that PHPUnit Symfony Bridge does anything with method declarations.

2021-05-31 10:32 UTC, emodric commented
I can try working around it somehow, but do we really need PHPStan here, since the repo is pretty much is maintenance mode?

2021-05-31 10:37 UTC, Steveb-p commented
@emodric it makes sense to have it, even at this stage. There are already inconsistencies detected for ezplatform-kernel that were found by it.

Let me see what I can do in the evening. Worst case I'll disable PHPStan checks on PHP8 and we'll see how it goes.

2021-06-17 07:07 UTC, emodric commented
Hi @Steveb-p . Any progress on this?

Thanks!

2021-06-17 07:42 UTC, Steveb-p commented
> Hi @Steveb-p . Any progress on this?
> 
> Thanks!

I forgot to get back to this. I'll set a reminder for myself and will take a look tomorrow evening.

2021-06-22 11:48 UTC, Steveb-p commented
@emodric sorry for the late response. I've moved your email notification (GH) into important directory in my mailbox, and then wasn't able to find it, because I've forgotten I've moved it.

Derp.

The solution for the CI issue is simple: remove 9.x PHPUnit from the list of `require-dev`. This will cause the version 7.x to be installed, which is compatible in every way with symfony/cache 3.x.

This should make the tests green. I've tested it against PHP 7.4.

2021-06-23 07:46 UTC, Steveb-p commented
Travis had some sort of a hiccup and needed the job to be restarted. Tests are green now.

2021-06-23 07:57 UTC, adamwojs approved these changes

2021-06-23 08:23 UTC, alongosz approved these changes

2021-06-23 08:26 UTC, Steveb-p commented on phpunit.xml.dist
> +        <env name="SYMFONY_PHPUNIT_REMOVE_RETURN_TYPEHINT" value="1" />
No longer needed.

```suggestion
```

2021-06-23 09:23 UTC, emodric commented
@Steveb-p Thanks for seeing this to the end :) I suppose you will tag 1.0.5 as soon as this is merged?

2021-06-23 09:43 UTC, Steveb-p commented
@emodric Probably something like that - it's technically a bugfix. There is hardly a BC break, since it wasn't working on PHP8 anyway (where covariance and contravariance requirement is hardened).

I'm not usually the one doing the version releases though.

2021-06-23 10:37 UTC, merged